services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: buildclip-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - buildclip-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: buildclip-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - buildclip-network

networks:
  buildclip-network:
    driver: bridge

volumes:
  buildclip-data:
